### ISSUE TITLE
[snap] Does not work darktable with wayland session Edit

### ISSUE THREAD

**Issue by caravena** [sergiusens/darktable-snap#12] opened 2018-05-29 19:25 UTC
Hello,

Open bug in launchpad.net
https://bugs.launchpad.net/bugs/1774050

"Does not work darktable with wayland session. I'm working with https://github.com/kyrofa/darktable-snap"

Regards,
--
Cristian Aravena Romero (caravena)

**Comment by kyrofa** [comment] 2018-08-02 17:43
Does Darktable work with Wayland period?

**Comment by bitsandsalsa** [comment] 2018-09-05 01:02
I believe so. I installed version 2.4.2 (this was the latest in the standard Ubuntu 18.04 APT repo) and ran it in a Wayland session. Additionally, the [2.4.0 release notes](https://github.com/darktable-org/darktable/releases/tag/release-2.4.0) mention support for being a Wayland client, albeit an XWayland one.

**Comment by bitsandsalsa** [comment] 2018-09-06 18:02
Found a workaround. TL;DR - Run darktable with environment variable DISABLE_WAYLAND set to something.

Looks like the issue is with the _desktop-launch_ script that gets generated from the [desktop-gtk3](https://github.com/ubuntu/snapcraft-desktop-helpers) part. [Wayland detection](https://github.com/ubuntu/snapcraft-desktop-helpers/blob/master/common/desktop-exports) ends up [setting](https://github.com/ubuntu/snapcraft-desktop-helpers/blob/master/gtk/launcher-specific) GDK_BACKEND to `wayland`. It will work if set to `x11`.

I'm not sure if a fix is warranted in this snap, the _desktop-gtk_ part, or documented somewhere and left as an exercise for the user if they choose to run under Wayland?

**Comment by kyrofa** [comment] 2018-09-06 18:06
@bitsandsalsa that's an excellent discovery! The `desktop-gtk` part is in the middle of a refactor, I'll make sure this is accounted for there.

**Comment by sergiusens** [comment] 2022-04-02 11:47
This was fixed in https://github.com/sergiusens/darktable-snap/commit/d69fda6adf0b75f7a14f6a1a87b074982cea45cc

**Closed by sergiusens** 2022-04-02 11:47 UTC
